//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ACMS
{
    using System;
    using System.Collections.Generic;
    
    public partial class AccessLevelsDoors
    {
        public int idAccessLevelDoor { get; set; }
        public int idAccessLevel { get; set; }
        public int idDoor { get; set; }
    
        public virtual AccessLevels AccessLevels { get; set; }
        public virtual Doors Doors { get; set; }
    }
}
