//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ACMS
{
    using System;
    using System.Collections.Generic;
    
    public partial class CurrentUser
    {
        public int idCurrentUser { get; set; }
        public int idUser { get; set; }
        public byte SaveOrNo { get; set; }
    
        public virtual Users Users { get; set; }
    }
}
