//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ACMS
{
    using System;
    using System.Collections.Generic;
    
    public partial class DoorsEmployees
    {
        public int idDoorEmployee { get; set; }
        public int idDoor { get; set; }
        public int idEmployee { get; set; }
        public System.DateTime EnterDateTime { get; set; }
    
        public virtual Doors Doors { get; set; }
        public virtual Employees Employees { get; set; }
    }
}
