//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ACMS
{
    using System;
    using System.Collections.Generic;
    
    public partial class Keys
    {
        public int idKey { get; set; }
        public int idEmployee { get; set; }
        public string KeyCard { get; set; }
        public int idAccessLevel { get; set; }
        public int idWorkSchedule { get; set; }
    
        public virtual Employees Employees { get; set; }
        public virtual WorkSchedules WorkSchedules { get; set; }
    }
}
