//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ACMS
{
    using System;
    using System.Collections.Generic;
    
    public partial class Payments
    {
        public int idPayment { get; set; }
        public int idTypePayment { get; set; }
        public int idProduct { get; set; }
    
        public virtual Products Products { get; set; }
        public virtual TypesPayments TypesPayments { get; set; }
    }
}
