//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ACMS.ApplicationData
{
    using System;
    using System.Collections.Generic;
    
    public partial class AccessLevelsDoors
    {
        public int idDAL { get; set; }
        public int idAL { get; set; }
        public int idD { get; set; }
    
        public virtual AccessLevels AccessLevels { get; set; }
        public virtual Doors Doors { get; set; }
    }
}
