//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ACMS.ApplicationData
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class ACMSEntities : DbContext
    {
        public ACMSEntities()
            : base("name=ACMSEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<AccessLevels> AccessLevels { get; set; }
        public virtual DbSet<AccessLevelsDoors> AccessLevelsDoors { get; set; }
        public virtual DbSet<BlackList> BlackList { get; set; }
        public virtual DbSet<Departments> Departments { get; set; }
        public virtual DbSet<DoorDirections> DoorDirections { get; set; }
        public virtual DbSet<Doors> Doors { get; set; }
        public virtual DbSet<DoorsEmployees> DoorsEmployees { get; set; }
        public virtual DbSet<Employees> Employees { get; set; }
        public virtual DbSet<Keys> Keys { get; set; }
        public virtual DbSet<Organizations> Organizations { get; set; }
        public virtual DbSet<Users> Users { get; set; }
        public virtual DbSet<WorkSchedules> WorkSchedules { get; set; }
    }
}
