//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ACMS.ApplicationData
{
    using System;
    using System.Collections.Generic;
    
    public partial class BlackList
    {
        public int idBL { get; set; }
        public int idE { get; set; }
        public System.DateTime EnterDate { get; set; }
    
        public virtual Employees Employees { get; set; }
    }
}
