//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ACMS.ApplicationData
{
    using System;
    using System.Collections.Generic;
    
    public partial class DoorsEmployees
    {
        public int idDE { get; set; }
        public int idD { get; set; }
        public int idE { get; set; }
        public System.DateTime EnterDateTime { get; set; }
    }
}
