//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ACMS.ApplicationData
{
    using System;
    using System.Collections.Generic;
    
    public partial class Employees
    {
        public int idE { get; set; }
        public string Fistname { get; set; }
        public string Secondname { get; set; }
        public string Patronymic { get; set; }
        public int idD { get; set; }
        public int idO { get; set; }
    }
}
