//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ACMS.ApplicationData
{
    using System;
    using System.Collections.Generic;
    
    public partial class WorkSchedules
    {
        public int idWS { get; set; }
        public string TitleWS { get; set; }
        public System.TimeSpan StartDay { get; set; }
        public System.TimeSpan EndDay { get; set; }
    }
}
